### ISSUE TITLE
Add required minimum PHP version

### ISSUE THREAD

**Issue by peter279k** [alexkart/curl-builder#1]
As title, it seems that this package misses the minimum PHP version requirement inside `require` block.

It seems that the minimum PHP version is `7.1` because it uses the `"phpunit/phpunit": "^7.2"` at least.

It should define the ` "php": "^7.1"` inside `require` block in `composer.json`.

Here is the [PHPUnit 7.2 references](https://phpunit.de/getting-started/phpunit-7.html).

**Comment by alexkart** [comment]
@peter279k, thanks, will add the requirement.

**Comment by alexkart** [comment]
Added the requirement `"php": "^7.1"`
