### ISSUE TITLE
Use RequestInterface instead of ServerRequestInterface

### ISSUE THREAD

**Issue by xepozz** [alexkart/curl-builder#7]
I see in https://github.com/alexkart/curl-builder/blob/master/src/Command.php#L389-L417 and think that `Psr\Http\Message\RequestInterface` is enough for this parsing.

Shall I make PR?

**Comment by alexkart** [comment]
Hi @xepozz , I'm not sure I understand what you mean. Can you explain?

**Comment by xepozz** [comment]
I mean the `ServerRequestInterface` could be replaced with `RequestInterface`

**Comment by alexkart** [comment]
OK, you can make a PR.

**Comment by xepozz** [comment]
https://github.com/alexkart/curl-builder/pull/8

**Comment by xepozz** [comment]
Could you also make a release?

**Comment by alexkart** [comment]
> Could you also make a release?

Will do.

**Comment by alexkart** [comment]
https://github.com/alexkart/curl-builder/releases/tag/1.0.7

**Comment by xepozz** [comment]
Great. Thank you!
